export const GET_MY_COOPS_REQUEST = "GET_MY_COOPS_REQUEST"
export const GET_MY_COOPS_SUCCESS = "GET_MY_COOPS_SUCCESS"
export const GET_MY_COOPS_FAIL = "GET_MY_COOPS_FAIL"



export const GET_COOP_DETAIL_REQUEST = "GET_COOP_DETAIL_REQUEST"
export const GET_COOP_DETAIL_SUCCESS = "GET_COOP_DETAIL_SUCCESS"
export const GET_COOP_DETAIL_FAIL = "GET_COOP_DETAIL_FAIL"


export const GET_RESULT_REQUEST = "GET_RESULT_REQUEST"
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS"
export const GET_RESULT_FAIL = "GET_RESULT_FAIL"
export const GET_RESULT_RESET = "GET_RESULT_RESET"


export const SEARCH_COOP_REQUEST = "SEARCH_COOP_REQUEST"
export const SEARCH_COOP_SUCCESS = "SEARCH_COOP_SUCCESS"
export const SEARCH_COOP_FAIL = "SEARCH_COOP_FAIL"
export const SEARCH_COOP_RESET = "SEARCH_COOP_RESET"
