export const GET__USER__ACCOUNT__REQUEST =  "GET__USER__ACCOUNT__REQUEST"
export const GET__USER__ACCOUNT__SUCCESS =  "GET__USER__ACCOUNT__SUCCESS"
export const GET__USER__ACCOUNT__FAIL =  "GET__USER__ACCOUNT__FAIL"
export const GET__USER__ACCOUNT__RESET ="GET__USER__ACCOUNT__RESET"